### ISSUE TITLE
Program type already present: com.pdftron.pdf.tools.BuildConfig issue when creating build apk.

### ISSUE THREAD

**Issue by priyanka114** [PDFTron/pdftron-android-samples#5]
I am upgrading my pdf-trone library. It was jar file previously now I am using  "implementation 'com.pdftron:pdftron:7.0.3'" as dependancy. It works fine when i run app directly but when I try to build the apk it gives me following error.

"Program type already present: com.pdftron.pdf.tools.BuildConfig". What could be the reason for it or any solution for this.

**Comment by brandenfung2** [comment]
Since this issue does not seem to be related to the samples in this repository, would it be possible if you could send us a support ticket at https://www.pdftron.com/support/ ? Also, it would be helpful if you could send us your build.gradle file so that we can take a closer look.
